os: linux
group: edge

addons:
    apt:
        packages:
          - libdbus-1-dev
          - libudev-dev
          - libdbus-glib-1-dev
          # needed for i686-unknown-linux-gnu target
          - gcc-multilib
          - python3-pyudev

language: rust

matrix:
    fast_finish: true
    allow_failures:
        # Allow beta tasks to fail
        - rust: beta
        # Allow nightly tasks to fail
        - rust: nightly
        # Allow audit task to fail
        - env: TASK=audit
    include:

        # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
        # rustfmt
        - rust: 1.37.0
          before_script:
              - rustup component add rustfmt
          env: TASK=fmt-travis
        # clippy
        - rust: 1.37.0
          before_script:
              - rustup component add clippy
          env: TASK=clippy

        # MANDATORY TESTING USING LOWEST SUPPORTED COMPILER
        # tests
        - rust: 1.36.0
          env: TASK=test
        # release
        - rust: 1.36.0
          env: TASK=release


        # MANDATORY TESTING ON STABLE
        # compile
        - rust: stable
          env: TASK=build TARGET=x86_64-unknown-linux-gnu
        # compile with no defaults enabled
        - rust: stable
          env: TASK=build-no-default TARGET=x86_64-unknown-linux-gnu
        # compile on a 32-bit system
        - rust: stable
          env: TASK=build TARGET=i686-unknown-linux-gnu PKG_CONFIG_ALLOW_CROSS=1 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/
          install:
            - rustup target add $TARGET
            - sudo dpkg --add-architecture i386
            - sudo apt-get update
            - sudo apt-get install -y gcc-multilib libdbus-1-dev:i386 libdbus-glib-1-dev:i386 libglib2.0-dev:i386 libudev-dev:i386
        # Build docs
        - rust: stable
          env: TASK=docs-travis
        # test
        - rust: stable
          env: TASK=test
        # destructive tests that can be run on Travis
        - rust: stable
          env: TASK=test-travis
          sudo: required
        # release
        - rust: stable
          env: TASK=release


        # MANDATORY PYTHON CHECKS
        # Run pylint, Python linter, on any Python test code
        - dist: xenial
          language: python
          python: "3.7"
          install: pip3 install -r tests/client-dbus/requirements.txt
          before_script:
              - cd tests/client-dbus
          env: TASK=lint
        # Format any Python test code using yapf
        - language: python
          python: "3.7"
          install: pip3 install -r tests/client-dbus/requirements.txt
          before_script:
              - cd tests/client-dbus
          env: TASK=fmt-travis

        # ALLOWED FAILURES
        # Run clippy on rust beta, in order to be good Rustaceans
        - rust: beta
          before_script:
              - rustup component add clippy
          env: TASK=clippy
        # Run audit on Rust stable.  Make it an allowed failure, because:
        # * It takes 9 minutes, the longest of any task.
        # * It should be an advisory, and should not gate our development.
        - rust: stable
          env: TASK=audit
        # Run inspect on Rust nightly to have a quick and easy way to see
        # desugared stratisd source. This might help our understanding of
        # our ever more sugared source.
        - rust: nightly
          env: TASK=inspect

branches:
    only: master

script: make -f Makefile $TASK
